config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :repositories, only: [:index]
  get '/repositories/remote', to: 'repositories#remote'
  resources :dashboard, only: [:index]
  resources :followers, only: [:index]
  get '/followers/profile', to: 'followers#show'

  namespace :followers do
    resources :respositories, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/git_hub_user.rb
class GitHubUser

  @@AllUsers = Array.new
  attr_reader :login, :name, :avatar_url, :company, :location, :uid, :email

  def initialize(user)
    @login = user[:login]
    user_info = GitHubService.user_info(@login)
    @name = user_info[:name]
    @email = user_info[:email]
    @avatar_url = user_info[:avatar_url]
    @company = user_info[:company]
    @location = user_info[:location]
    @uid = user_info[:id].to_s
    @@AllUsers << self
  end

  def self.all_instances
    @@AllUsers
  end



  def self.find(uid)
    @@AllUsers.select do |instance|
      instance.uid == uid
    end
  end

  def all_repos
    page = 1
    one_page = ['no data']
    repos = []
    until one_page.count == 0
      one_page = GitHubService.generic_user_repos(self, page)
      repos += one_page
      page += 1
    end
    repos.map { |repo| Repo.new(repo) }
  end

  def self.my_repos(user)
    GitHubService.generic_user_repos(user, page = 1).map do |raw_repo|
      Repo.new(raw_repo)
    end
  end
end

app/models/repo.rb
class Repo
  attr_reader :name, :url, :owner

  def initialize(repo)
    @name = repo[:name]
    @url = repo[:html_url]
    @owner = repo[:owner][:id].to_s
  end
end

app/models/user.rb
class User < ApplicationRecord

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.login              = auth_info.extra.raw_info.login
      new_user.avatar_url         = auth_info.extra.raw_info.avatar_url
      new_user.email              = auth_info.extra.raw_info.email
      new_user.repos_url          = auth_info.extra.raw_info.repos_url
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end

  def all_repos
    page = 1
    one_page = ['no data']
    repos = []
    until one_page.count == 0
      one_page = GitHubService.authenticated_user_repos(self, page)
      repos += one_page
      page += 1
    end
    repos.map { |repo| Repo.new(repo) }
  end

  def my_repos
    repos = all_repos
    repos.map do |repo|
      repo if repo.owner == uid
    end.compact
  end

  def my_repos_elsewhere
    repos = all_repos
    repos.map do |repo|
      repo if repo.owner != uid
    end.compact
  end

  def followers
    GitHubService.followers(self).map do |user|
      GitHubUser.new(user)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/followers/repositories_controller.rb
class Followers::RepositoriesController < ApplicationController
  def index
    @repos = GitHubUser.my_repos(params[:uid])
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @followers = current_user.followers
  end

  def show
    @git_hub_user = GitHubUser.find(params[:uid]).first
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_index_path if current_user
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  def index
    # @repos = current_user.my_repos
    @repos = GitHubUser.my_repos(current_user)
  end

  def remote
    @repos = current_user.my_repos_elsewhere
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
      redirect_to dashboard_index_path
    else
      render_template root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<div class="row">

  <%= render 'shared/profile' %>

  <div class="col-md-9">

    <%= render 'shared/mini_nav' %>

  </div>

</div>

app/views/followers/index.html.erb
<div class="row">

  <%= render 'shared/profile' %>

  <div class="col-md-9">

    <%= render 'shared/mini_nav' %>


    <% @followers.each do |follower| %>
      <div class="row repository_row">
          <div class="col-md-3">
            <h3><a href="<%- followers_profile_path(uid: follower.uid) %>"><image src="<%= follower.avatar_url -%>"></image></a></h3>
          </div>
          <div class="col-md-9">
            <div class="row follower_row">
              <p>
                <%= link_to follower.name, followers_profile_path(uid: follower.uid) %>     <%= follower.login %>
              </p>
            </div>
            <div class="row follower_row_2">
              <p>
                <%= follower.company %>     <%= follower.location %>
              </p>
            </div>
          </div>
      </div>
    <% end %>

  </div>

</div>

app/views/followers/show.html.erb
<div class="row">

  <div class="col-md-3">
    <div class="row profile_img">
      <image src="<%= @git_hub_user.avatar_url %>"></image>
    </div>

    <div class="row">
      <h1><%= @git_hub_user.name %></h1>
    </div>

    <div class="row login_hp">
        <p><%= @git_hub_user.login %></p>
    </div>

    <div class="row mail_img">
        <image src='assets/mail'></image><span><%= @git_hub_user.email %></span>
    </div>

  </div>


  <div class="col-md-9">

    <%= render 'shared/mini_nav' %>

  </div>

</div>

app/views/home/index.html.erb
<%= link_to "Login With Git Hub", github_login_path %>

app/views/layouts/_navbar.html.erb
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href='/' class="navbar-brand octocat"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Pull Requests</a></li>
        <li><a href="#">Issues</a></li>
        <li><a href="#">Gist</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><image src="<%= current_user.avatar_url if current_user %>" height="20"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Signed in as <%= current_user.login if current_user %></a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Your Profile</a></li>
            <li><a href="#">Your Stats</a></li>
            <li><a href="#">Explore</a></li>
            <li><a href="#">Integrations</a></li>
            <li><a href="#">Help</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Settings</a></li>
            <li><%= link_to "Sign Out", logout_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApicuriousGithub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <nav class="navbar navbar-default">
    <div class="container">
      <%= render "layouts/navbar" %>
    </div>
  </nav>

<div class= "container">
  <body>
    <%= yield %>
  </body>
</div>

</html>

app/views/repositories/_repo_list.html.erb
<% @repos.each do |repo| %>
  <div class="row">
    <div class="repository_row">
      <h3><%= link_to repo.name, repo.url %></h3>
    </div>
  </div>
<% end %>

app/views/repositories/index.html.erb
<div class="row">

  <%= render 'shared/profile' %>

  <div class="col-md-9">
    <div class="mini_nav">
      <table class="table">
          <thead>
            <tr>
              <th><%= link_to "Repositories", repositories_path %></th>
              <th><%= link_to "Repositories", repositories_path %></th>
              <th><%= link_to "Repositories", repositories_path %></th>
            </tr>
          </thead>
      </table>
    </div>

      <!-- <div class="mininav_box">
        <%= link_to "Repositories", repositories_path %>
      </div> -->

    <% @repos.each do |repo| %>
      <div class="row">
        <div class="repository_row">
          <h3><%= repo[:name] %></h3>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/repositories/remote.html.erb
<div class="row">

  <%= render 'shared/profile' %>

  <div class="col-md-9">

    <%= render 'shared/mini_nav' %>

    <%= render 'repo_list' %>

  </div>

</div>

app/views/shared/_mini_nav.html.erb
  <div class="mini_nav">
    <table class="table">
        <thead>
          <tr>
            <th><%= link_to "Repositories", repositories_path %></th>
            <th><%= link_to "Remote Repositories", repositories_remote_path %></th>
            <th><%= link_to "Followers", followers_path %></th>
            <th></th>
          </tr>
        </thead>
    </table>

app/views/shared/_profile.html.erb
<div class="col-md-3">
  <div class="row profile_img">
    <image src="<%= current_user.avatar_url %>"></image>
  </div>

  <div class="row">
    <h1><%= current_user.name %></h1>
  </div>

  <div class="row login_hp">
      <p><%= current_user.login %></p>
  </div>
  
  <div class="row mail_img">
      <image src='assets/mail'></image><span><%= current_user.email %></span>
  </div>

</div>